name: 'build-and-release'
on:
  workflow_dispatch:

jobs:
  build-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-20.04, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: 'StackBaker/stackbaker'
          token: ${{ secrets.PAT_TOKEN }}
        
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: setup pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 7.30.3

      - name: Rust setup
        uses: dtolnay/rust-toolchain@stable
      
      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'
      
      - name: Install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf
        
      - name: Install frontend dependencies
        run: pnpm install

      - name: Build the app
        uses: tauri-apps/tauri-action@0300c0cf6d20920d0812a6af9e624aadec51cacd
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
          ENABLE_CODE_SIGNING: ${{ secrets.APPLE_CERTIFICATE }}
          APPLE_CERTIFICATE: ${{ secrets.APPLE_CERTIFICATE }}
          APPLE_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
          APPLE_SIGNING_IDENTITY: ${{ secrets.APPLE_SIGNING_IDENTITY }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_PASSWORD: ${{ secrets.APPLE_PASSWORD }}
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
        with:
          tagName: v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version
          releaseName: 'StackBaker Desktop v__VERSION__'
          releaseBody: 'StackBaker now has an auto-updater. A few minor bugs are also fixed in this version.'
          releaseDraft: false
          prerelease: false
          includeDebug: true # publish only debug versions for now
          includeRelease: false
  
  update-website-links:
    name: "Dispatch update links workflow to website repo"
    needs: build-tauri
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch update links workflow to website repo
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PAT_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'StackBaker',
              repo: 'website',
              workflow_id: 'update_release_links.yml',
              ref: 'master'
            })
