name: 'update-website-links'
on:
  workflow_dispatch:

jobs:
  update-website-links:
    name: "Dispatch update links workflow to website repo"
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch update links workflow to website repo
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PAT_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'StackBaker',
              repo: 'website',
              workflow_id: 'update_release_links.yml',
              ref: 'main'
            })
